packages:
  - packages/api
  - packages/bitcoin
  - packages/cli
  - packages/common
  - packages/cryptosuite
  - packages/keypair
  - packages/key-manager
  - packages/method
  - packages/smt

allowBuilds:
  '@ipshipyard/node-datachannel': true
  classic-level: true
  esbuild: true

onlyBuiltDependencies:
  - "@ipshipyard/node-datachannel"
  - classic-level
  - dtrace-provider
  - esbuild
  - node-datachannel
