#!/usr/bin/env node
/**
 * `pnpm wallet` CLI dispatcher.
 *
 * A persistent dev-tool wallet for did:btcr2 test vector generation across
 * regtest, mutinynet, signet, and testnet4. Funds beacons from a single funding
 * key; sweeps unused sats back; tracks every key in the user config directory
 * (`~/.config/did-btcr2-js/wallet/wallet.json` on Linux/macOS).
 *
 * Commands:
 *   init     create the funding key and wallet.json
 *   add      register a new beacon key (generated or imported)
 *   list     list registered keys + addresses for one network
 *   status   fetch live balances per key per address type
 *   fund     send sats from the funding key to a beacon key or raw address
 *   recover  sweep a beacon address back to the funding key
 *   send     generic transfer: any wallet key (or secret-hex file) to any
 *            label or raw address; --amount or --all (sweep)
 */
import { Command } from 'commander';

import { cmdAdd } from './commands/add.js';
import { cmdFund } from './commands/fund.js';
import { cmdInit } from './commands/init.js';
import { cmdList } from './commands/list.js';
import { cmdRecover } from './commands/recover.js';
import { cmdSend } from './commands/send.js';
import { cmdStatus } from './commands/status.js';

const program = new Command();

program
  .name('wallet')
  .description('did:btcr2 test-network wallet (regtest / mutinynet / signet / testnet4)')
  .version('0.1.0');

program
  .command('init')
  .description('create the funding key and initialize wallet.json')
  .option('-n, --network <name>', 'default network: regtest|mutinynet|signet|testnet4', 'mutinynet')
  .option('--force', 'overwrite an existing wallet.json (DESTRUCTIVE)')
  .action(async (opts) => cmdInit(opts));

program
  .command('add <label>')
  .description('register a new beacon key (generated by default)')
  .option('-s, --scenario <id>', 'link this key to a test scenario id')
  .option('--secret <hex>', 'import an existing 32-byte secret instead of generating')
  .option('--notes <text>', 'free-form notes saved alongside the key')
  .action(async (label, opts) => cmdAdd(label, opts));

program
  .command('list')
  .description('list registered keys with addresses')
  .option('-n, --network <name>', 'show addresses for this network instead of the default')
  .action(async (opts) => cmdList(opts));

program
  .command('status')
  .description('fetch live UTXO balances for every key on the active network')
  .option('-n, --network <name>', 'query this network instead of the default')
  .action(async (opts) => cmdStatus(opts));

program
  .command('fund <labelOrAddress>')
  .description('send sats from the funding key to a registered beacon key or a raw address')
  .option('-a, --amount <sats>', 'amount to send', '10000')
  .option('-t, --addr-type <kind>', 'destination address type for labels: p2pkh|p2wpkh|p2tr', 'p2wpkh')
  .option('-n, --network <name>', 'network to broadcast on')
  .option('-f, --fee-rate <sat-per-vb>', 'fee rate override (default 1)')
  .action(async (labelOrAddress, opts) => cmdFund(labelOrAddress, opts));

program
  .command('send <from> <to>')
  .description('send sats from any wallet key (funding, a label, or a secret-hex file) to a label or raw address')
  .option('-a, --amount <sats>', 'amount to send (exactly one of --amount / --all)')
  .option('--all', 'sweep: send everything at the source address, minus fee')
  .option('--from-type <kind>', 'source address type: p2pkh|p2wpkh|p2tr', 'p2wpkh')
  .option('--to-type <kind>', 'destination address type for labels: p2pkh|p2wpkh|p2tr', 'p2wpkh')
  .option('-n, --network <name>', 'network to broadcast on')
  .option('-f, --fee-rate <sat-per-vb>', 'fee rate override (default 1)')
  .action(async (from, to, opts) => cmdSend(from, to, opts));

program
  .command('recover <label>')
  .description('sweep a beacon address back to the funding key')
  .option('-t, --addr-type <kind>', 'source address type: p2pkh|p2wpkh|p2tr', 'p2wpkh')
  .option('-n, --network <name>', 'network to broadcast on')
  .option('-f, --fee-rate <sat-per-vb>', 'fee rate override (default 1)')
  .action(async (label, opts) => cmdRecover(label, opts));

try {
  await program.parseAsync(process.argv);
} catch (err) {
  console.error(`\n  ERROR: ${(err as Error).message}\n`);
  process.exit(1);
}
