import { sha256 } from "@noble/hashes/sha2";

const BIP340_PUBLIC_KEY_MULTIBASE_PREFIX = new Uint8Array([0xe7, 0x01]);
const BIP340_PUBLIC_KEY_MULTIBASE_PREFIX_HASH = sha256(BIP340_PUBLIC_KEY_MULTIBASE_PREFIX);
BIP340_PUBLIC_KEY_MULTIBASE_PREFIX_HASH.toHex();
