import { canonicalHash, canonicalize, hash } from '@did-btcr2/common';
import { SignedBTCR2Update } from '@did-btcr2/cryptosuite';
import { BTCR2MerkleTree, SerializedSMTProof, TreeEntry } from '@did-btcr2/smt';
import { keyAggExport, keyAggregate, sortKeys } from '@scure/btc-signer/musig2';
import { payments, Transaction } from 'bitcoinjs-lib';
import { BeaconCoordinatorError } from '../../beacon/error.js';
import { CASAnnouncement } from '../../types.js';
import { BeaconCohortSigningSession } from '../session/index.js';
import { BeaconCohortReadyMessage } from './messages/keygen/cohort-ready.js';
import { BeaconCohortRequestSignatureMessage } from './messages/sign/request-signature.js';
import { COHORT_STATUS, COHORT_STATUS_TYPE } from './status.js';

export type Musig2CohortObject = {
    id?: string;
    coordinatorDid?: string;
    minParticipants?: number;
    status?: COHORT_STATUS_TYPE;
    network: string;
    beaconType?: string;
}

export interface BeaconCohort {
  id?: string;
  coordinatorDid: string;
  minParticipants: number;
  status: COHORT_STATUS_TYPE;
  network: string;
  pendingSignatureRequests?: Record<string, string>;
  pendingUpdates?: Map<string, SignedBTCR2Update>;
  casAnnouncement?: CASAnnouncement;
  smtProofs?: Map<string, SerializedSMTProof>;
  signalBytes?: Uint8Array;
  participants?: Array<string>;
  cohortKeys?: Array<Uint8Array>;
  trMerkleRoot?: Uint8Array;
  beaconAddress?: string;
}

export class AggregateBeaconCohort implements BeaconCohort {
  /**
   * Unique identifier for the cohort.
   * @type {string}
   */
  public id: string;

  /**
   * DID of the coordinator.
   * @type {string}
   */
  public coordinatorDid: string;

  /**
   * Minimum number of participants required to finalize the cohort.
   * @type {number}
   */
  public minParticipants: number;

  /**
   * Status of the cohort.
   * @type {string}
   */
  public status: COHORT_STATUS_TYPE;

  /**
   * Network on which the cohort operates (e.g., 'mainnet', 'testnet').
   * @type {string}
   */
  public network: string;

  /**
   * Pending signature requests, mapping participant DIDs to their pending signatures.
   * @type {Record<string, string>}
   */
  public pendingSignatureRequests: Record<string, string> = {};

  /**
   * List of participant DIDs.
   * @type {Array<string>}
   */
  public participants: Array<string> = new Array<string>();

  /**
   * List of cohort keys.
   * @type {Array<Uint8Array>}
   */
  public _cohortKeys: Array<Uint8Array> = new Array<Uint8Array>();

  /**
   * Taproot Merkle root for the cohort.
   * @type {Uint8Array}
   */
  public trMerkleRoot: Uint8Array = new Uint8Array();

  /**
   * Beacon address for the cohort, calculated from the Taproot multisig.
   * @type {string}
   */
  public beaconAddress: string = '';

  /**
   * Type of beacon used in the cohort (default is 'SMTBeacon').
   * @type {string}
   */
  public beaconType: string;

  /**
   * Pending DID updates submitted by participants during the Announce Updates phase.
   * Keyed by participant DID, valued by their signed update.
   * @type {Map<string, SignedBTCR2Update>}
   */
  public pendingUpdates: Map<string, SignedBTCR2Update> = new Map();

  /**
   * Built CAS Announcement mapping participant DIDs to their update hashes.
   * Populated by buildCASAnnouncement() after all updates are collected.
   * @type {CASAnnouncement}
   */
  public casAnnouncement?: CASAnnouncement;

  /**
   * Per-participant SMT proofs generated by buildSMTTree().
   * Keyed by participant DID, valued by their serialized Merkle inclusion proof.
   * @type {Map<string, SerializedSMTProof>}
   */
  public smtProofs?: Map<string, SerializedSMTProof>;

  /**
   * Signal bytes to commit on-chain (hash of aggregated data structure).
   * For CAS beacons: SHA-256 of the canonicalized CAS Announcement.
   * For SMT beacons: the Merkle root hash.
   * @type {Uint8Array}
   */
  public signalBytes?: Uint8Array;

  /**
   * Creates a new Musig2Cohort instance.
   * @param {Musig2CohortObject} params Parameters for initializing the cohort.
   * @param {string} [params.id] Optional unique identifier for the cohort. If not provided, a random UUID will be generated.
   * @param {number} params.minParticipants Minimum number of participants required to finalize the cohort.
   * @param {string} [params.coordinatorDid] DID of the coordinator managing the cohort.
   * @param {string} params.status Initial status of the cohort (e.g., 'PENDING', 'COHORT_SET').
   * @param {string} params.network Network on which the cohort operates (e.g., 'mainnet', 'testnet').
   */
  constructor({ id, minParticipants, coordinatorDid, status, network, beaconType }: Musig2CohortObject) {
    this.id = id || crypto.randomUUID();
    this.minParticipants = minParticipants || 2;
    this.coordinatorDid = coordinatorDid || '';
    this.status = status as COHORT_STATUS_TYPE || COHORT_STATUS.COHORT_ADVERTISED;
    this.network = network;
    this.beaconType = beaconType || 'SMTBeacon';
  }

  set cohortKeys(keys: Array<Uint8Array>) {
    this.cohortKeys = sortKeys(keys);
  }

  public validateCohort(participantKeys: Array<string>, cohortKeys: Array<string>, beaconAddress: string): void {
    for(const key of participantKeys){
      if(!cohortKeys.includes(key)) {
        this.status = COHORT_STATUS.COHORT_FAILED;
        throw new BeaconCoordinatorError(
          `Participant key ${key} not found in cohort ${this.id}.`,
          'COHORT_VALIDATION_ERROR',
          {
            cohortId        : this.id,
            participantKeys : participantKeys,
            cohortKeys      : cohortKeys,
            beaconAddress   : beaconAddress
          }
        );
      }
    }
    this.cohortKeys = cohortKeys.map(key => Buffer.from(key, 'hex'));
    const calculatedAddress = this.calulateBeaconAddress();
    if (calculatedAddress !== beaconAddress) {
      this.status = COHORT_STATUS.COHORT_FAILED;
      throw new BeaconCoordinatorError(
        `Calculated beacon address ${calculatedAddress} does not match provided address ${beaconAddress}.`,
        'COHORT_ADDRESS_MISMATCH_ERROR',
        {
          cohortId        : this.id,
          calculatedAddress,
          providedAddress : beaconAddress
        }
      );
    }
    this.beaconAddress = beaconAddress;
    this.status = COHORT_STATUS.COHORT_SET_STATUS;
  }

  /**
   * Finalizes the cohort by checking if the minimum number of participants is met.
   * If the minimum is met, it sets the status to 'COHORT_SET_STATUS' and calculates the beacon address.
   * @throws {BeaconCoordinatorError} If the number of participants is less than the minimum required.
   * @returns {void}
   */
  public finalize(): void {
    if(this.participants.length < this.minParticipants) {
      throw new BeaconCoordinatorError(
        'Not enough participants to finalize the cohort',
        'FINALIZE_COHORT_ERROR',
        {
          cohortId        : this.id,
          participants    : this.participants,
          minParticipants : this.minParticipants
        }
      );
    }
    this.status = COHORT_STATUS.COHORT_SET_STATUS;
    this.beaconAddress = this.calulateBeaconAddress();
  }

  /**
   * Calculates the beacon Taproot multisig address for the cohort using participant keys.
   * @returns {string} The Taproot address for the cohort.
   * @throws {BeaconCoordinatorError} If the Taproot address cannot be calculated.
   */
  public calulateBeaconAddress(): string {
    const keyAggContext = keyAggregate(this.cohortKeys);
    const aggPubkey = keyAggExport(keyAggContext);
    const payment = payments.p2tr({ internalPubkey: aggPubkey });
    if(!payment.hash) {
      throw new BeaconCoordinatorError(
        'Failed to calculate Taproot Merkle root',
        'CALCULATE_BEACON_MERKLE_ROOT_ERROR',
        {
          cohortId        : this.id,
          cohortKeys      : this.cohortKeys,
          minParticipants : this.minParticipants
        }
      );
    }
    this.trMerkleRoot = payment.hash;
    if(!payment.address) {
      throw new BeaconCoordinatorError(
        'Failed to calculate Taproot address',
        'CALCULATE_BEACON_ADDRESS_ERROR',
        {
          cohortId        : this.id,
          cohortKeys      : this.cohortKeys,
          minParticipants : this.minParticipants
        }
      );
    }
    return payment.address;
  }

  /**
   * Generates a CohortReadyMessage to be sent to participants when the cohort is set.
   * @param {string} to The DID of the participant to whom the message is sent.
   * @param {string} from The DID of the coordinator sending the message.
   * @returns {BeaconCohortReadyMessage} The CohortReadyMessage containing the cohort details.
   */
  public getCohortReadyMessage(to: string, from: string): BeaconCohortReadyMessage {
    if(this.status !== COHORT_STATUS.COHORT_SET_STATUS) {
      throw new BeaconCoordinatorError('Cohort status not "COHORT_SET".');
    }
    return new BeaconCohortReadyMessage({
      to,
      from,
      cohortId      : this.id,
      beaconAddress : this.beaconAddress,
      cohortKeys    : this.cohortKeys,
    });
  }

  /**
   * Adds a signature request to the pending requests for the cohort.
   * @param {BeaconCohortRequestSignatureMessage} message The signature request message to add.
   * @throws {Error} If a signature request from the same participant already exists.
   */
  public addSignatureRequest(message: BeaconCohortRequestSignatureMessage): void {
    if(!this.validateSignatureRequest(message)) {
      throw new BeaconCoordinatorError(`No signature request from ${message.from} in cohort ${this.id}.`);
    }

    if(!message.body?.data) {
      throw new BeaconCoordinatorError(`No signature data in request from ${message.from} in cohort ${this.id}.`);
    }

    this.pendingSignatureRequests[message.from] = message.body.data;
  }

  /**
   * Adds a signed DID update from a participant during the Announce Updates phase.
   * Transitions the cohort to COLLECTING_UPDATES on the first update, and to
   * UPDATES_COLLECTED once all participants have submitted.
   * @param {string} participantDid The DID of the participant submitting the update.
   * @param {SignedBTCR2Update} signedUpdate The participant's signed update.
   * @throws {BeaconCoordinatorError} If the participant is not in the cohort or the cohort
   *   is not in a valid state for accepting updates.
   */
  public addUpdate(participantDid: string, signedUpdate: SignedBTCR2Update): void {
    if(this.status !== COHORT_STATUS.COHORT_SET_STATUS && this.status !== COHORT_STATUS.COLLECTING_UPDATES) {
      throw new BeaconCoordinatorError(
        `Cohort ${this.id} is not accepting updates. Current status: ${this.status}`,
        'UPDATE_SUBMISSION_ERROR', { cohortId: this.id, status: this.status }
      );
    }

    if(!this.participants.includes(participantDid)) {
      throw new BeaconCoordinatorError(
        `Participant ${participantDid} is not in cohort ${this.id}.`,
        'UPDATE_SUBMISSION_ERROR', { cohortId: this.id, participantDid }
      );
    }

    if(this.pendingUpdates.has(participantDid)) {
      console.warn(`Update already received from ${participantDid} for cohort ${this.id}. Replacing.`);
    }

    this.pendingUpdates.set(participantDid, signedUpdate);

    if(this.status === COHORT_STATUS.COHORT_SET_STATUS) {
      this.status = COHORT_STATUS.COLLECTING_UPDATES;
    }

    if(this.hasAllUpdates()) {
      this.status = COHORT_STATUS.UPDATES_COLLECTED;
    }
  }

  /**
   * Checks whether all participants have submitted their updates.
   * @returns {boolean} True if all participants have submitted updates.
   */
  public hasAllUpdates(): boolean {
    return this.pendingUpdates.size === this.participants.length;
  }

  /**
   * Builds a CAS Announcement from collected participant updates.
   * Maps each participant DID to the base64url-encoded canonical hash of their signed update.
   * Computes signal bytes as the SHA-256 hash of the canonicalized announcement.
   * Transitions the cohort to DATA_AGGREGATED status.
   *
   * @returns {CASAnnouncement} The built CAS Announcement.
   * @throws {BeaconCoordinatorError} If updates have not been fully collected.
   */
  public buildCASAnnouncement(): CASAnnouncement {
    if(this.status !== COHORT_STATUS.UPDATES_COLLECTED) {
      throw new BeaconCoordinatorError(
        `Cannot build CAS Announcement: cohort ${this.id} status is ${this.status}, expected UPDATES_COLLECTED.`,
        'AGGREGATION_ERROR', { cohortId: this.id, status: this.status }
      );
    }

    const announcement: CASAnnouncement = {};
    for(const [did, signedUpdate] of this.pendingUpdates) {
      announcement[did] = canonicalHash(signedUpdate);
    }

    this.casAnnouncement = announcement;
    this.signalBytes = hash(canonicalize(announcement));
    this.status = COHORT_STATUS.DATA_AGGREGATED;

    return announcement;
  }

  /**
   * Builds a BTCR2MerkleTree from collected participant updates.
   * For each participant DID, generates a random 32-byte nonce and inserts an
   * inclusion entry with the canonicalized signed update bytes. After finalization,
   * stores the root hash as signalBytes and generates per-participant SMT proofs.
   * Transitions the cohort to DATA_AGGREGATED status.
   *
   * @returns {Map<string, SerializedSMTProof>} Per-participant SMT proofs keyed by DID.
   * @throws {BeaconCoordinatorError} If updates have not been fully collected.
   */
  public buildSMTTree(): Map<string, SerializedSMTProof> {
    if(this.status !== COHORT_STATUS.UPDATES_COLLECTED) {
      throw new BeaconCoordinatorError(
        `Cannot build SMT tree: cohort ${this.id} status is ${this.status}, expected UPDATES_COLLECTED.`,
        'AGGREGATION_ERROR', { cohortId: this.id, status: this.status }
      );
    }

    const tree = new BTCR2MerkleTree();
    const entries: TreeEntry[] = [];
    const encoder = new TextEncoder();

    for(const [did, signedUpdate] of this.pendingUpdates) {
      const canonicalBytes = encoder.encode(canonicalize(signedUpdate));
      const nonce = crypto.getRandomValues(new Uint8Array(32));
      entries.push({ did, nonce, signedUpdate: canonicalBytes });
    }

    tree.addEntries(entries);
    tree.finalize();

    this.signalBytes = tree.rootHash;
    this.smtProofs = new Map();

    for(const [did] of this.pendingUpdates) {
      this.smtProofs.set(did, tree.proof(did));
    }

    this.status = COHORT_STATUS.DATA_AGGREGATED;
    return this.smtProofs;
  }

  /**
   * Validates a signature request message to ensure it is from a participant in the cohort.
   * @param {BeaconCohortRequestSignatureMessage} message The signature request message to validate.
   * @returns {boolean} True if the message is valid, false otherwise.
   */
  public validateSignatureRequest(message: BeaconCohortRequestSignatureMessage): boolean {
    const cohortId = message.body?.cohortId;
    if(cohortId !== this.id) {
      console.info(`Signature request for wrong cohort: ${cohortId}.`);
      return false;
    }

    if(!this.participants.includes(message.from)) {
      console.info(`Participant ${message.from} not in cohort ${this.id}.`);
      return false;
    }

    return true;
  }

  /**
   * Starts a signing session for the cohort.
   * @returns {BeaconCohortSigningSession} The request signature message for the signing session.
   */
  public startSigningSession(): BeaconCohortSigningSession {
    console.debug(`Starting signing session for cohort ${this.id} with status ${this.status}`);
    if(this.status !== COHORT_STATUS.COHORT_SET_STATUS) {
      throw new BeaconCoordinatorError(`Cohort ${this.id} is not set.`);
    }
    // const smtRootBytes = new Uint8Array(32).map(() => Math.floor(Math.random() * 256));
    const cohort = new AggregateBeaconCohort(this);
    return new BeaconCohortSigningSession({
      cohort,
      pendingTx         : new Transaction(),
      processedRequests : this.pendingSignatureRequests,
    });
  }

  /**
   * Converts the cohort instance to a JSON object representation.
   * @returns {BeaconCohort} The JSON object representation of the cohort.
   */
  public toJSON(): BeaconCohort {
    return {
      id                       : this.id,
      coordinatorDid           : this.coordinatorDid,
      minParticipants          : this.minParticipants,
      status                   : this.status,
      network                  : this.network,
      pendingSignatureRequests : this.pendingSignatureRequests,
      pendingUpdates           : this.pendingUpdates,
      casAnnouncement          : this.casAnnouncement,
      smtProofs                : this.smtProofs,
      signalBytes              : this.signalBytes,
      participants             : this.participants,
      cohortKeys               : this.cohortKeys,
      trMerkleRoot             : this.trMerkleRoot,
      beaconAddress            : this.beaconAddress,
    };
  }
}