export type COHORT_STATUS_TYPE =
  | 'ADVERTISED'
  | 'OPTED_IN'
  | 'COHORT_SET'
  | 'COLLECTING_UPDATES'
  | 'UPDATES_COLLECTED'
  | 'DATA_AGGREGATED'
  | 'FAILED';

export enum COHORT_STATUS {
  COHORT_ADVERTISED = 'ADVERTISED',
  COHORT_OPTED_IN = 'OPTED_IN',
  COHORT_SET_STATUS = 'COHORT_SET',
  COLLECTING_UPDATES = 'COLLECTING_UPDATES',
  UPDATES_COLLECTED = 'UPDATES_COLLECTED',
  DATA_AGGREGATED = 'DATA_AGGREGATED',
  COHORT_FAILED = 'FAILED',
}